github.com:
    users:
        Zlatovlaska11:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Zlatovlaska11
